apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: radarr
    app.kubernetes.io/name: radarr
    app.kubernetes.io/part-of: arrs
  name: radarr
spec:
  serviceName: radarr
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
      app.kubernetes.io/part-of: arrs
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
        app.kubernetes.io/name: radarr
        app.kubernetes.io/part-of: arrs
    spec:
      containers:
        - env:
            - name: PGID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: TZ
              value: America/New_York
          image: linuxserver/radarr:5.14.0
          name: radarr
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /movies
              name: Movies
            - mountPath: /downloads
              name: MovieDownloads
      restartPolicy: Always
      volumes:
        - name: radarr-config
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: nfs-subdir-external-provisioner
            resources:
              requests:
                storage: 1Gi
        - name: Movies
          nfs:
            server: 172.16.0.5
            path: /volume1/Movies
        - name: MovieDownloads
          nfs:
            server: 172.16.0.5
            path: /volume1/downloads/radarr
