apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phpipam
resources:
  - namespace.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - phpipam-db-pv.yaml
  - phpipam-db-pvc.yaml
  - phpipam-db-statefulset.yaml
  - phpipam-cron-deployment.yaml
  - phpipam-web-deployment.yaml
  - service.yaml
  - ingressroute.yaml
