apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-data
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: authentik
spec:
  storageClassName: longhorn
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
