---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-redis-data
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: authentik
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: authentik-redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-data
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: authentik
spec:
  storageClassName: longhorn-static
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
