---
# Source: plex-media-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tdarr-webui
  labels:
    app: tdarr-server
spec:
  type: ClusterIP
  ports:
    - port: 8265
      targetPort: tdarr-webui
      protocol: TCP
      name: tdarr-webui
  selector:
    app: tdarr-server
