---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ombi
  labels:
    app: ombi
    part-of: media
  annotations:
    cert-manager.io/cluster-issuer: external
    # nginx.ingress.kubernetes.io/auth-url: |-
    #   http://ak-outpost-nginx-ingress.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    # # If you're using domain-level auth, use the authentication URL instead of the application URL
    # nginx.ingress.kubernetes.io/auth-signin: |-
    #   https://$host/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
    # nginx.ingress.kubernetes.io/auth-response-headers: |-
    #   Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    # nginx.ingress.kubernetes.io/auth-snippet: |
    #   proxy_set_header X-Forwarded-Host $http_host;
    # traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: ombi
    gethomepage.dev/group: Media
    gethomepage.dev/icon: ombi.png
    gethomepage.dev/name: Ombi
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_OMBI_API_KEY}}"
    gethomepage.dev/widget.type: "ombi"
    gethomepage.dev/widget.url: "https://ombi.home.8none1.com/ombi"
    gethomepage.dev/pod-selector: ""
spec:
  ingressClassName: nginx
  rules:
    - host: ombi.home.8none1.com
      http:
        paths:
          - path: /ombi
            pathType: Prefix
            backend:
              service:
                name: ombi
                port:
                  name: http
  tls:
    - hosts:
        - ombi.home.8none1.com
      secretName: ombi-ingress-tls
