---
apiVersion: v1
kind: Service
metadata:
  name: ombi
  labels:
    app: ombi
    part-of: media
spec:
  selector:
    app: ombi
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: ombi
