---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-proxy
  namespace: proxies
  labels:
    app: files-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files-proxy
  template:
    metadata:
      labels:
        app: files-proxy
    spec:
      containers:
        - name: socat
          image: alpine/socat
          args:
            - TCP4-LISTEN:443,fork,reuseaddr
            - TCP4:172.16.1.5:5001
          ports:
            - containerPort: 443
              name: https
---
apiVersion: v1
kind: Service
metadata:
  name: files-proxy
spec:
  type: ClusterIP
  selector:
    app: files-proxy
  ports:
    - name: https
      port: 443
      targetPort: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: files-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`files.home.8none1.com`)
      kind: Rule
      services:
        - name: files-proxy
          port: https
          scheme: https
          serversTransport: files-proxy-transport
  tls:
    secretName: files-proxy-ingress-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: files-proxy-transport
spec:
  insecureSkipVerify: true
  serverName: files.home.8none1.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: files-proxy-ingress-tls
  namespace: proxies
  labels:
    app: files-proxy
spec:
  secretName: files-proxy-ingress-tls
  issuerRef:
    name: external
    kind: ClusterIssuer
  dnsNames:
    - files.home.8none1.com
