---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant
  namespace: proxies
subsets:
  - addresses:
      - ip: 172.16.0.50
    ports:
      - port: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: proxies
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: proxies
  annotations:
    cert-manager.io/cluster-issuer: external
    external-dns.alpha.kubernetes.io/hostname: ha.home.8none1.com
spec:
  ingressClassName: nginx
  rules:
    - host: ha.home.8none1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassistant
                port:
                  name: http
  tls:
    - hosts:
        - ha.home.8none1.com
      secretName: homeassistant-ingress-tls
