---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: socat
          image: alpine/socat
          args:
            - TCP4-LISTEN:8123,fork,reuseaddr
            - TCP4:172.16.0.50:8123
          ports:
            - containerPort: 8123
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: ClusterIP
  selector:
    app: homeassistant
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: proxies
  annotations:
    cert-manager.io/cluster-issuer: external
    external-dns.alpha.kubernetes.io/hostname: ha.home.8none1.com
spec:
  rules:
    - host: ha.home.8none1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassistant
                port:
                  name: http
  tls:
    - hosts:
        - ha.home.8none1.com
      secretName: homeassistant-ingress-tls
