apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: radarr-api-key
