apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-api-keys
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: homepage
    app.kubernetes.io/managed-by: kustomize
  annotations:
    force-sync: "1751314172"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: radarr-api-key
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: sonarr-api-key
    - secretKey: HOMEPAGE_VAR_PROWLARR_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: prowlarr-api-key
    # - secretKey: HOMEPAGE_VAR_TDARR_API_KEY
    #   remoteRef:
    #     key: homepage-api-keys
    #     property: tdarr-api-key
    - secretKey: HOMEPAGE_VAR_PLEX_TOKEN
      remoteRef:
        key: homepage-api-keys
        property: plex-token
    - secretKey: HOMEPAGE_VAR_TAUTULLI_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: tautulli-api-key
    - secretKey: HOMEPAGE_VAR_OVERSEERR_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: overseerr-api-key
    - secretKey: HOMEPAGE_VAR_MAINTAINERR_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: maintainerr-api-key
    - secretKey: HOMEPAGE_VAR_SABNZBD_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: sabnzbd-api-key
    - secretKey: HOMEPAGE_VAR_AUTHENTIK_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: authentik-api-key
    - secretKey: HOMEPAGE_VAR_UNIFI_PASSWORD
      remoteRef:
        key: homepage-api-keys
        property: unifi-homepage-password
    - secretKey: HOMEPAGE_VAR_CALIBRE_HOMEPAGE_PASSWORD
      remoteRef:
        key: homepage-api-keys
        property: calibre-homepage-password
