apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-api-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: radarr-api-key
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: homepage-api-keys
        property: sonarr-api-key
    - secretKey: HOMEPAGE_VAR_PLEX_TOKEN
      remoteRef:
        key: homepage-api-keys
        property: plex-token
