---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage

resources:
  - namespace.yaml
  - externalsecret.yaml
  - rbac.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - authentik-middleware.yaml
