---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "8Gi"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: homepage-public
# spec:
#   accessModes:
#     - "ReadWriteMany"
#   resources:
#     requests:
#       storage: "8Gi"
