---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: homepage
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "8Gi"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: homepage-public
# spec:
#   accessModes:
#     - "ReadWriteMany"
#   resources:
#     requests:
#       storage: "8Gi"
