---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-frontend-ingress-tls
spec:
  secretName: longhorn-frontend-ingress-tls
  issuerRef:
    name: external
    kind: ClusterIssuer
  commonName: longhorn.home.8none1.com
  dnsNames:
    - longhorn.home.8none1.com