apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn-system
  namespace: longhorn-system

namespace: longhorn-system

helmCharts:
  - name: longhorn
    version: 1.9.0
    repo: https://charts.longhorn.io
    releaseName: longhorn
    includeCRDs: true
    valuesFile: values.yaml
    namespace: longhorn-system
    skipHooks: true
    skipTests: true

resources:
  - namespace.yaml
  # - https://raw.githubusercontent.com/longhorn/longhorn/v1.9.0/deploy/longhorn.yaml
  # - ingress.yaml
  - certificate.yaml
  - authentik-middleware.yaml
  - ingressroute.yaml
