---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tautulli-config-longhorn
  labels:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: media-tautulli-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tautulli-config
  labels:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: media-tautulli-config-longhorn
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
