# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh API credentials secret

# apiVersion: v1
# kind: Secret
# metadata:
#   name: indexer-cred
# data:
#   username: YWRtaW4=              # string "admin" base64 encoded
#   password: U2VjcmV0UGFzc3dvcmQ=  # string "SecretPassword" base64 encoded

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: indexer-cred
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: wazuh-indexer-cred
        property: username
    - key: password
      remoteRef:
        key: wazuh-indexer-cred
        property: password
