# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh authd password secret

# apiVersion: v1
# kind: Secret
# metadata:
#   name: wazuh-authd-pass
#   namespace: wazuh
# data:
#   authd.pass: cGFzc3dvcmQ= # string "password" base64 encoded

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-authd-pass
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: authd.pass
      remoteRef:
        key: wazuh-authd-pass
        property: authd.pass
