apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfd-control-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfd-control-plane
subjects:
  - kind: ServiceAccount
    name: nfd-control-plane
    namespace: node-feature-discovery
