apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfd-control-plane
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
    verbs:
      - get
      - patch
      - update
      - list
  - apiGroups:
      - nfd.k8s-sigs.io
    resources:
      - nodefeatures
      - nodefeaturerules
      - nodefeaturegroups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - nfd.k8s-sigs.io
    resources:
      - nodefeaturegroup/status
    verbs:
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resourceNames:
      - nfd-control-plane.nfd.kubernetes.io
    resources:
      - leases
    verbs:
      - get
      - update
