apiVersion: v1
kind: Service

metadata:
  name: authentik-outpost
  namespace: media
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 9000
  externalName: ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local
