apiVersion: v1
kind: Service

metadata:
  name: authentik-outpost
  namespace: media
spec:
  type: ExternalName
  externalName: ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local
  ports:
    - name: http
      port: 9000
      targetPort: 9000
