apiVersion: v1
kind: Service
metadata:
  name: authentik-outpost
  namespace: authentik
spec:
  type: ExternalName
  externalName: authentik-ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local
