apiVersion: v1
kind: Service

metadata:
  name: authentik-outpost
  namespace: media
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/component: "server"
