---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-env.yaml
  - persistentvolumes.yaml
  - pvc.yaml
  - authentik-service.yaml
  # Radarr
  - radarr/statefulset.yaml
  - radarr/service.yaml
  - radarr/ingress.yaml
