---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - namespace.yaml
  - persistentvolumes.yaml
  - pvc.yaml
  # Radarr
  - radarr/pvc.yaml
  - radarr/statefulset.yaml
  - radarr/service.yaml
  - radarr/ingressroute.yaml
  # Sonarr
  - sonarr/pvc.yaml
  - sonarr/statefulset.yaml
  - sonarr/service.yaml
  - sonarr/ingressroute.yaml
  # Prowlarr
  - prowlarr/pvc.yaml
  - prowlarr/service.yaml
  - prowlarr/statefulset.yaml
  - prowlarr/ingressroute.yaml
  # Overseerr
  - overseerr/service.yaml
  - overseerr/statefulset.yaml
  - overseerr/ingressroute.yaml
  - overseerr/pvc.yaml
  # Maintainerr
  - maintainerr/service.yaml
  - maintainerr/statefulset.yaml
  - maintainerr/ingressroute.yaml
  - maintainerr/pvc.yaml
  # Tautulli
  - tautulli/service.yaml
  - tautulli/statefulset.yaml
  - tautulli/ingressroute.yaml
  - tautulli/pvc.yaml
  # SanNZBd
  - sabnzbd/ingressroute.yaml
  - sabnzbd/service.yaml
  - sabnzbd/statefulset.yaml
  - sabnzbd/pvc.yaml
  # Tdarr
  - tdarr/ingressroute.yaml
  - tdarr/service.yaml
  - tdarr/statefulset.yaml
  - tdarr/pvc.yaml
  # Plex
  - plex
  # Kavita
  - kavita/service.yaml
  - kavita/statefulset.yaml
  - kavita/ingressroute.yaml
  - kavita/pvc.yaml
  # Calibre
  - calibre/service.yaml
  - calibre/statefulset.yaml
  - calibre/ingressroute.yaml
  - calibre/pvc.yaml
  # Autnentik Middleware
  - authentik-middleware.yaml

configMapGenerator:
  - name: arr-init-config
    files:
      - init-scripts/arr-init-config.sh
  - name: arr-env
    files:
      - env/arr.env
# generatorOptions:
#   disableNameSuffixHash: true
