---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - namespace.yaml
  - persistentvolumes.yaml
  - pvc.yaml
  # Radarr
  - radarr/pvc.yaml
  - radarr/statefulset.yaml
  - radarr/service.yaml
  - radarr/ingress.yaml
  # Sonarr
  - sonarr/pvc.yaml
  - sonarr/statefulset.yaml
  - sonarr/service.yaml
  - sonarr/ingress.yaml
  # Prowlarr
  - prowlarr/pvc.yaml
  - prowlarr/service.yaml
  - prowlarr/statefulset.yaml
  - prowlarr/ingress.yaml
  # Overseerr
  - overseerr/service.yaml
  - overseerr/statefulset.yaml
  - overseerr/ingress.yaml
  - overseerr/pvc.yaml
  # Ombi
  # - ombi/service.yaml
  # - ombi/statefulset.yaml
  # - ombi/ingress.yaml
  # - ombi/pvc.yaml
  # Maintainerr
  - maintainerr/service.yaml
  - maintainerr/statefulset.yaml
  - maintainerr/ingress.yaml
  - maintainerr/pvc.yaml
  # Tautulli
  - tautulli/service.yaml
  - tautulli/statefulset.yaml
  - tautulli/ingress.yaml
  - tautulli/pvc.yaml
  # SanNZBd
  - sabnzbd
  # Tdarr
  - tdarr
  - plex
  # Kavita
  - kavita/service.yaml
  - kavita/statefulset.yaml
  - kavita/ingress.yaml
  - kavita/pvc.yaml
  # Calibre
  - calibre/service.yaml
  - calibre/statefulset.yaml
  - calibre/ingress.yaml
  - calibre/pvc.yaml
  # Autnentik Middleware
  - authentik-middleware.yaml

configMapGenerator:
  - name: arr-init-config
    files:
      - init-scripts/arr-init-config.sh
  - name: arr-env
    files:
      - env/arr.env
# generatorOptions:
#   disableNameSuffixHash: true
