---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - namespace.yaml
  - persistentvolumes.yaml
  - pvc.yaml
  # Radarr
  - radarr/pvc.yaml
  - radarr/statefulset.yaml
  - radarr/service.yaml
  - radarr/ingress.yaml
  # Sonarr
  - sonarr/pvc.yaml
  - sonarr/statefulset.yaml
  - sonarr/service.yaml
  - sonarr/ingress.yaml
  # - plex

configMapGenerator:
  - name: arr-init-config
    files:
      - init-scripts/arr-init-config.sh
  - name: arr-env
    files:
      - env/arr.env
# generatorOptions:
#   disableNameSuffixHash: true
