---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
  namespace: media
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - sync
  nfs:
    path: /volume1/Movies
    server: 172.16.0.5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
  namespace: media
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - sync
  nfs:
    path: /volume1/TV
    server: 172.16.0.5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-movies
  namespace: media
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - sync
  nfs:
    path: /volume1/HomeMovies
    server: 172.16.0.5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  namespace: media
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - sync
  nfs:
    path: /volume1/downloads
    server: 172.16.0.5
