---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
  labels:
    app: media
    volume: movies
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - sync
  nfs:
    path: /volume1/Movies
    server: 172.16.0.5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
  labels:
    app: media
    volume: tv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - sync
  nfs:
    path: /volume1/TV
    server: 172.16.0.5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-movies
  labels:
    app: media
    volume: home-movies
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - sync
  nfs:
    path: /volume1/HomeMovies
    server: 172.16.0.5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  labels:
    app: media
    volume: downloads
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - sync
  nfs:
    path: /volume1/downloads
    server: 172.16.0.5
