---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  labels:
    app: media
    part-of: media
    volume: movies
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: media
      part-of: media
      volume: movies
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
  labels:
    app: media
    part-of: media
    volume: tv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: media
      part-of: media
      volume: tv
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-movies
  labels:
    app: media
    part-of: media
    volume: home-movies
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: media
      part-of: media
      volume: home-movies
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  labels:
    app: media
    part-of: media
    volume: music
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: media
      part-of: media
      volume: music
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books
  labels:
    app: media
    part-of: media
    volume: books
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: media
      part-of: media
      volume: books
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  labels:
    app: media
    part-of: media
    volume: downloads
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: media
      part-of: media
      volume: downloads
  resources:
    requests:
      storage: 10Ti
