apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd
  namespace: media
spec:
  secretName: sabnzbd-ingress-tls
  issuerRef:
    name: external
    kind: ClusterIssuer
  commonName: sabnzbd.home.8none1.com
  dnsNames:
    - sabnzbd.home.8none1.com