apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sabnzbd.home.8none1.com
    external-dns.alpha.kubernetes.io/target: traefik.srv.8none1.com
  labels:
    app: sabnzbd
    part-of: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sabnzbd.home.8none1.com`)
      kind: Rule
      services:
        - name: sabnzbd
          port: 8080
      middlewares:
        - name: authentik-forward-auth
          namespace: media
  tls:
    secretName: sabnzbd-ingress-tls