---
# Source: plex-media-server/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-server
  labels:
    app: plex-server
  annotations:
    cert-manager.io/cluster-issuer: external
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Plex is HTTP (change to HTTPS if applicable)
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # Allow large media files
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600" # Handle long streams
    external-dns.alpha.kubernetes.io/hostname: plex.home.8none1.com
spec:
  ingressClassName: nginx
  rules:
    - host: plex.home.8none1.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: plex-server
                port:
                  name: plex-server
  tls:
    - hosts:
        - plex.home.8none1.com
      secretName: plex-server-ingress-tls
