# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   annotations:
#     pv.kubernetes.io/provisioned-by: csi.san.synology.com
#   name: plex-server-config
#   labels:
#     app: plex-server
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 200Gi
#   csi:
#     driver: csi.san.synology.com
#     volumeHandle: 815b0b69-58d9-4155-b773-0a6887cf791f
#   volumeMode: Filesystem
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: synology-iscsi-storage
# ---
# # Source: phpipam/templates/pvc.yaml
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-server-config
#   labels:
#     app: plex-server
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 200Gi
#   storageClassName: synology-iscsi-storage
#   volumeName: plex-server-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-plex-server-config-longhorn
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: media-plex-server-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-plex-server-config
  namespace: media
spec:
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
  volumeName: media-plex-server-config-longhorn
  accessModes:
    - ReadWriteOnce
