---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.san.synology.com
  name: plex-server-config
  labels:
    app: plex-server
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: csi.san.synology.com
    volumeHandle: 815b0b69-58d9-4155-b773-0a6887cf791f
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: synology-iscsi-storage
---
# Source: phpipam/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-server-config
  labels:
    app: plex-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: synology-iscsi-storage
  volumeName: plex-server-config
