---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-plex-server-config-longhorn
  labels:
    app.kubernetes.io/name: plex-server
    app.kubernetes.io/instance: plex-server
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: media-plex-server-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-plex-server-config
  labels:
    app.kubernetes.io/name: plex-server
    app.kubernetes.io/instance: plex-server
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
spec:
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
  volumeName: media-plex-server-config-longhorn
  accessModes:
    - ReadWriteOnce
