---
# Source: plex-media-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plex-server
  annotations:
    metallb.io/loadBalancerIPs: 172.16.1.151
  labels:
    app.kubernetes.io/name: plex-server
    app.kubernetes.io/instance: plex-server
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ports:
    - port: 32400
      targetPort: plex-server
      protocol: TCP
      name: plex-server
  selector:
    app.kubernetes.io/name: plex-server
    app.kubernetes.io/instance: plex-server
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
