---
# Source: plex-media-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-server
  labels:
    app.kubernetes.io/name: plex-server
    app.kubernetes.io/instance: plex-server
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
