---
# Source: plex-media-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plex-server
  labels:
    app: plex-server
spec:
  type: ClusterIP
  ports:
    - port: 32400
      targetPort: plex-server
      protocol: TCP
      name: plex-server
  selector:
    app: plex-server
