---
# Source: plex-media-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plex-server
  labels:
    app: plex-server
spec:
  type: ClusterIP
  ports:
    - port: 32400
      targetPort: plex-server
      protocol: TCP
      name: plex-server
  selector:
    app: plex-server
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/loadBalancerIPs: 172.16.1.151
  labels:
    app: plex-server
  name: plex-external-service
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ports:
    - name: plex-external
      port: 32400
      protocol: TCP
      targetPort: plex-server
  selector:
    app: plex-server
