---
# Source: plex-media-server/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-server
  labels:
    app: plex-server
spec:
  serviceName: plex-server
  selector:
    matchLabels:
      app: plex-server
  template:
    metadata:
      labels:
        app: plex-server
    spec:
      serviceAccountName: plex-server
      volumes:
        - name: plex-server-config
          persistentVolumeClaim:
            claimName: plex-server-config
        - name: plex-server-transcode
          emptyDir: {}
        - name: movies
          persistentVolumeClaim:
            claimName: movies
        - name: tv
          persistentVolumeClaim:
            claimName: tv
        - name: music
          persistentVolumeClaim:
            claimName: music
        - name: home-movies
          persistentVolumeClaim:
            claimName: home-movies
      terminationGracePeriodSeconds: 120
      containers:
        - name: plex-server
          image: index.docker.io/plexinc/pms-docker:1.41.3.9314-a0bfb8370
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 32400
              name: plex-server
          resources:
            requests:
              cpu: 500m
              memory: 3Gi
              gpu.intel.com/i915: "1"
            limits:
              cpu: 1000m
              memory: 5Gi
              gpu.intel.com/i915: "1"
          env:
            - name: ADVERTISE_IP
              value: https://plex.home.8none1.com
            - name: PLEX_UID
              value: "1030"
            - name: PLEX_GID
              value: "65536"
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: plex-server-config
              mountPath: /config
            - name: plex-server-transcode
              mountPath: /transcode
            - name: movies
              mountPath: /mnt/Movies
            - name: tv
              mountPath: /mnt/TV
            - name: home-movies
              mountPath: /mnt/HomeMovies
            - name: music
              mountPath: /mnt/Music
  # volumeClaimTemplates:
  #   - metadata:
  #       name: plex-server-config
  #       namespace: media
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 20Gi
