---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cm-internal-intermediate-ca
  namespace: "authentik"
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: cm-internal-intermediate-fullchain.crt
      remoteRef:
        key: cm-internal-intermediate-ca
        property: cm-internal-intermediate-fullchain.crt
