---
# Source: paperless-ngx/charts/tika/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tika
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: tika
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
