---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-calibre-config-longhorn
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/instance: calibre
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: media
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: media-calibre-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-calibre-config
  namespace: media
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/instance: calibre
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: media
spec:
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  volumeName: media-calibre-config-longhorn
  accessModes:
    - ReadWriteOnce
