---
apiVersion: v1
kind: Service
metadata:
  name: calibre
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/instance: calibre
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/instance: calibre
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: calibre
