apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/instance: calibre
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
spec:
  serviceName: calibre
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: calibre
      app.kubernetes.io/instance: calibre
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: media
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calibre
        app.kubernetes.io/instance: calibre
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: media
    spec:
      containers:
        - image: linuxserver/calibre-web:0.6.24-ls316
          name: calibre
          env:
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-calibre
            - name: ENABLE_API
              value: "true"
          envFrom:
            - configMapRef:
                name: arr-env
          volumeMounts:
            - mountPath: /config
              name: calibre-config
            - mountPath: /books
              name: books
          ports:
            - name: calibre
              containerPort: 8083
              protocol: TCP
      volumes:
        - name: books
          persistentVolumeClaim:
            claimName: books
        - name: calibre-config
          persistentVolumeClaim:
            claimName: media-calibre-config
      restartPolicy: Always
