---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
  labels:
    app: paperless-ngx
    part-of: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: postgres-user-password
      remoteRef:
        key: paperless-ngx-config
        property: postgres-user-password
    - secretKey: postgres-postgres-password
      remoteRef:
        key: paperless-ngx-config
        property: postgres-postgres-password
    - secretKey: postgres-user
      remoteRef:
        key: paperless-ngx-config
        property: postgres-user
