---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: postgres-user-password
      remoteRef:
        key: paperless-ngx-config
        property: postgres-user-password
    - secretKey: postgres-postgres-password
      remoteRef:
        key: paperless-ngx-config
        property: postgres-postgres-password
    - secretKey: postgres-user
      remoteRef:
        key: paperless-ngx-config
        property: postgres-user
