---
# Source: paperless-ngx/charts/postgresql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql
  labels:
    app: postgresql
    part-of: paperless-ngx
automountServiceAccountToken: false
