---
apiVersion: v1
kind: Service
metadata:
  name: kavita
  labels:
    app.kubernetes.io/name: kavita
    app.kubernetes.io/instance: kavita
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: kavita
    app.kubernetes.io/instance: kavita
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: kavita
