apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: kavita
    app.kubernetes.io/instance: kavita
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
  name: kavita
spec:
  serviceName: kavita
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kavita
      app.kubernetes.io/instance: kavita
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: media
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kavita
        app.kubernetes.io/instance: kavita
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: media
    spec:
      containers:
        - image: linuxserver/kavita:v0.8.4.2-ls64
          name: kavita
          envFrom:
            - configMapRef:
                name: arr-env
          volumeMounts:
            - mountPath: /config
              name: kavita-config
            - mountPath: /data
              name: books
          ports:
            - name: kavita
              containerPort: 5000
              protocol: TCP
      volumes:
        - name: books
          persistentVolumeClaim:
            claimName: books
        - name: kavita-config
          persistentVolumeClaim:
            claimName: media-kavita-config
      restartPolicy: Always
