---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-authentik-secrets
  namespace: vikunja
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: onepassword-clustersecretstore
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: VIKUNJA_AUTH_OPENID_AUTHENTIK_CLIENTID
      remoteRef:
        key: vikunja-secrets
        property: authentik-clientid
    - secretKey: VIKUNJA_AUTH_OPENID_AUTHENTIK_CLIENTSECRET
      remoteRef:
        key: vikunja-secrets
        property: authentik-clientsecret
