apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: maintainerr
    app.kubernetes.io/instance: maintainerr
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
  name: maintainerr
spec:
  serviceName: maintainerr
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: maintainerr
      app.kubernetes.io/instance: maintainerr
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: media
  template:
    metadata:
      labels:
        app.kubernetes.io/name: maintainerr
        app.kubernetes.io/instance: maintainerr
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: media
    spec:
      containers:
        - image: jorenn92/maintainerr:2.18.1
          imagePullPolicy: IfNotPresent
          name: maintainerr
          envFrom:
            - configMapRef:
                name: arr-env
          volumeMounts:
            - mountPath: /opt/data
              name: maintainerr-config
          ports:
            - name: maintainerr
              containerPort: 6246
              protocol: TCP
      volumes:
        - name: maintainerr-config
          persistentVolumeClaim:
            claimName: media-maintainerr-config
      restartPolicy: Always
