---
# Source: authentik/templates/worker/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: "authentik"
  labels:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/component: "worker"
    app.kubernetes.io/part-of: "authentik"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: "authentik"
      app.kubernetes.io/component: "worker"
      app.kubernetes.io/part-of: "authentik"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "authentik"
        app.kubernetes.io/component: "worker"
        app.kubernetes.io/part-of: "authentik"
    spec:
      serviceAccountName: authentik
      terminationGracePeriodSeconds: 30
      containers:
        - name: worker
          image: ghcr.io/goauthentik/server:2024.10.1
          volumeMounts:
            - name: cm-internal-intermediate-ca
              mountPath: /usr/local/share/ca-certificates/cm-internal-intermediate-fullchain.crt
              subPath: cm-internal-intermediate-fullchain.crt
          imagePullPolicy: IfNotPresent
          args:
            - worker
          env:
            - name: SSL_CERT_DIR
              value: /usr/local/share/ca-certificates
          envFrom:
            - secretRef:
                name: authentik
          livenessProbe:
            exec:
              command:
                - ak
                - healthcheck
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - ak
                - healthcheck
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            exec:
              command:
                - ak
                - healthcheck
            failureThreshold: 60
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
      volumes:
        - name: cm-internal-intermediate-ca
          secret:
            secretName: cm-internal-intermediate-ca
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: "authentik"
                    app.kubernetes.io/component: "worker"
                    app.kubernetes.io/part-of: "authentik"
                topologyKey: kubernetes.io/hostname
      enableServiceLinks: true
