apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - namespace.yaml
  - ipaddresspool.yaml
  - l2advertisement.yaml
helmCharts:
  - name: metallb
    namespace: metallb-system
    releaseName: metallb
    repo: https://metallb.github.io/metallb
    valuesFile: values.yaml
    version: v0.15.2
