---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cm-internal-intermediate-ca
  namespace: "cert-manager"
  labels:
    app.kubernetes.io/name: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: cm-internal-intermediate-ca
        property: cm-internal-intermediate-fullchain.crt
    - secretKey: tls.key
      remoteRef:
        key: cm-internal-intermediate-ca
        property: cm-internal-intermediate-ca.key
