apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - internal-cluster-issuer/external-secret.yaml
  - internal-cluster-issuer/internal-cluster-issuer.yaml
  - external-cluster-issuer/external-secret.yaml
  - external-cluster-issuer/external-cluster-issuer.yaml
helmCharts:
  - name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    valuesFile: values.yaml
    version: v1.18.2
