apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: external
spec:
  acme:
    email: adam.h.herbert@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
