# ---
# # Source: phpipam/templates/pvc.yaml
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: phpipam-db-pvc
#   labels:
#     app: phpipam
#     component: mysql
#     part-of: phpipam
#     volume: phpipam-mysql
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 30Gi
#   storageClassName: synology-iscsi-storage
#   volumeName: phpipam-db-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpipam-postgres-data
  namespace: phpipam
  labels:
    app: postgresql
    part-of: phpipam
spec:
  storageClassName: longhorn-static
  volumeName: phpipam-postgres-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
