---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: phpipam-secrets
  labels:
    app: phpipam
    part-of: phpipam
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: phpipam-mysql-pass
      remoteRef:
        key: phpipam-config
        property: mysql-pass