---
# Source: nginx-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/loadBalancerIPs: 172.16.1.152
  labels:
    helm.sh/chart: nginx-ingress-4.11.3
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/version: "1.11.3"
    app.kubernetes.io/part-of: nginx-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/component: controller
