apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-ingress

configMapGenerator:
  - name: nginx-ingress-controller
    options:
      labels:
        app.kubernetes.io/name: nginx-ingress
        app.kubernetes.io/instance: nginx-ingress
        app: nginx-ingress
      disableNameSuffixHash: true
    literals:
      - allow-snippet-annotations=true
      - use-forwarded-headers=true
      - compute-full-forwarded-for=true
      - enable-real-ip=true

resources:
  - namespace.yaml
  - admission-webhooks/cert-manager.yaml
  - admission-webhooks/validating-webhook.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  # - controller-configmap.yaml
  - controller-deployment.yaml
  - controller-hpa.yaml
  - controller-ingressclass.yaml
  - controller-poddisruptionbudget.yaml
  - controller-role.yaml
  - controller-rolebinding.yaml
  - controller-service-webhook.yaml
  - controller-service.yaml
  - controller-serviceaccount.yaml
