---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-redis-data-longhorn
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: paperless-ngx-redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-redis-data
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  volumeName: paperless-ngx-redis-data-longhorn
  accessModes:
    - ReadWriteOnce
