---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.san.synology.com
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  csi:
    driver: csi.san.synology.com
    volumeHandle: dc472254-8acc-4b46-9a6a-92d6071cba34
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: synology-iscsi-storage
---
# Source: phpipam/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    app: redis
    part-of: paperless-ngx
    volume: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: synology-iscsi-storage
  volumeName: redis-data
