---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis
  labels:
    app: redis
    part-of: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: paperless-ngx-config
        property: redis-password
