---
# Source: paperless-ngx/charts/redis/templates/master/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: redis-master
  labels:
    app: redis
    part-of: paperless-ngx
