apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-data
  namespace: authentik
  labels:
    app: postgresql
    part-of: authentik
spec:
  storageClassName: longhorn
  volumeName: authentik-postgres-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
