---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-postgres-data
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: authentik
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: authentik-postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-data
  namespace: authentik
  labels:
    app: postgresql
    part-of: authentik
spec:
  storageClassName: longhorn-static
  volumeName: authentik-postgres-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
