---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: "authentik"
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/part-of: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: authentik-postgres
        property: postgres-password
    - secretKey: username
      remoteRef:
        key: authentik-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: authentik-postgres
        property: password
    - secretKey: dbname
      remoteRef:
        key: authentik-postgres
        property: dbname
