---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nfs-subdir-external-provisioner-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: NFS_SERVER
      remoteRef:
        key: nfs-subdir-external-provisioner-env
        property: NFS_SERVER
    - secretKey: NFS_PATH
      remoteRef:
        key: nfs-subdir-external-provisioner-env
        property: NFS_PATH
