---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: nfs-subdir-external-provisioner
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  pathPattern: "/${.PVC.namespace}-${.PVC.name}" # waits for nfs.io/storage-path annotation, if not specified will accept as empty string.
  onDelete: retain
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-local-path-storageclass
spec:
  template:
    spec:
      containers:
        - name: patch-local-path-storageclass
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl patch storageclass local-path -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "false"}}}'
      restartPolicy: OnFailure
  backoffLimit: 4
