apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-outpost-tls
  namespace: authentik
spec:
  secretName: authentik-outpost-tls
  issuerRef:
    name: external
    kind: ClusterIssuer
  commonName: home.8none1.com
  dnsNames:
    - home.8none1.com
    - "*.home.8none1.com"