---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets.yaml
  - rbac.yaml
  # Postgres Components
  - postgresql/secrets.yaml
  - postgresql/configmap.yaml
  - postgresql/service.yaml
  - postgresql/statefulset.yaml
  # Redis Components
  - redis/serviceaccount.yaml
  - redis/configmap.yaml
  - redis/service.yaml
  - redis/statefulset.yaml
  # Authentik Server Components
  - server/service.yaml
  - server/deployment.yaml
  - server/ingress.yaml
  - server/certificate.yaml
  # Authentik Worker Components
  - worker/deployment.yaml
