---
# Source: authentik/charts/serviceAccount/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik
  namespace: "authentik"
  labels:
    app.kubernetes.io/name: "serviceAccount"
    app.kubernetes.io/part-of: "authentik"
---
# Source: authentik/charts/serviceAccount/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authentik
  namespace: "authentik"
  labels:
    app.kubernetes.io/name: "serviceAccount"
    app.kubernetes.io/part-of: "authentik"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - configmaps
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - middlewares
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
---
# Source: authentik/charts/serviceAccount/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik
  namespace: "authentik"
  labels:
    app.kubernetes.io/name: "serviceAccount"
    app.kubernetes.io/part-of: "authentik"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authentik
subjects:
  - kind: ServiceAccount
    name: authentik
    namespace: "authentik"
---
# Source: authentik/charts/serviceAccount/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "authentik-authentik"
  labels:
    app.kubernetes.io/name: "serviceAccount"
    app.kubernetes.io/part-of: "authentik"
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
---
# Source: authentik/charts/serviceAccount/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "authentik-authentik"
  labels:
    app.kubernetes.io/name: "serviceAccount"
    app.kubernetes.io/part-of: "authentik"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "authentik-authentik"
subjects:
  - kind: ServiceAccount
    name: authentik
    namespace: "authentik"
