---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: "authentik"
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_EMAIL__FROM
      remoteRef:
        key: authentik-email
        property: username
    - secretKey: AUTHENTIK_EMAIL__HOST
      remoteRef:
        key: authentik-email
        property: AUTHENTIK_EMAIL__HOST
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: authentik-email
        property: password
    - secretKey: AUTHENTIK_EMAIL__PORT
      remoteRef:
        key: authentik-email
        property: AUTHENTIK_EMAIL__PORT
    - secretKey: AUTHENTIK_EMAIL__TIMEOUT
      remoteRef:
        key: authentik-email
        property: AUTHENTIK_EMAIL__TIMEOUT
    - secretKey: AUTHENTIK_EMAIL__USE_SSL
      remoteRef:
        key: authentik-email
        property: AUTHENTIK_EMAIL__USE_SSL
    - secretKey: AUTHENTIK_EMAIL__USE_TLS
      remoteRef:
        key: authentik-email
        property: AUTHENTIK_EMAIL__USE_TLS
    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        key: authentik-email
        property: username
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: authentik-postgres
        property: host
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: authentik-postgres
        property: dbname
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: authentik-postgres
        property: AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: authentik-postgres
        property: AUTHENTIK_POSTGRESQL__USER
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik-secrets
        property: AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_AUTHENTIK_LOG_LEVEL
      remoteRef:
        key: authentik-secrets
        property: AUTHENTIK_AUTHENTIK_LOG_LEVEL
    - secretKey: AAUTHENTIK_ERROR_REPORTING__ENABLED
      remoteRef:
        key: authentik-secrets
        property: AUTHENTIK_ERROR_REPORTING__ENABLED
    - secretKey: AUTHENTIK_ERROR_REPORTING__ENVIRONMENT
      remoteRef:
        key: authentik-secrets
        property: AUTHENTIK_ERROR_REPORTING__ENVIRONMENT
    - secretKey: AUTHENTIK_ERROR_REPORTING__SEND_PII
      remoteRef:
        key: authentik-secrets
        property: AUTHENTIK_ERROR_REPORTING__SEND_PII
    - secretKey: AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__ASN
      remoteRef:
        key: authentik-secrets
        property: AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__ASN
    - secretKey: AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__GEOIP
      remoteRef:
        key: authentik-secrets
        property: AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__GEOIP
    - secretKey: AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE
      remoteRef:
        key: authentik-secrets
        property: AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE
    - secretKey: AUTHENTIK_POSTGRESQL__PORT
      remoteRef:
        key: authentik-postgres
        property: AUTHENTIK_POSTGRESQL__PORT
    - secretKey: AUTHENTIK_REDIS__HOST
      remoteRef:
        key: authentik-secrets
        property: AUTHENTIK_REDIS__HOST
