---
# Source: external-dns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-unifi
  namespace: external-dns
  labels:
    app: external-dns
    instance: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
      instance: unifi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
        instance: unifi
    spec:
      serviceAccountName: external-dns-unifi
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: external-dns-unifi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          resources:
            requests:
              cpu: 100m # 0.1 CPU
              memory: 128Mi # 128 MB RAM
            limits:
              cpu: 250m # 0.25 CPU
              memory: 256Mi # 256 MB RAM
          image: registry.k8s.io/external-dns/external-dns:v0.18.0
          imagePullPolicy: IfNotPresent
          args:
            - --log-level=info
            - --interval=1m
            - --source=ingress
            - --source=service
            - --source=traefik-proxy
            - --traefik-disable-legacy
            - --policy=sync
            - --registry=txt
            - --txt-owner-id=default
            - --txt-prefix=k8s.
            - --domain-filter=8none1.com
            - --provider=webhook
          ports:
            - name: http
              protocol: TCP
              containerPort: 7979
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
        - name: webhook
          image: ghcr.io/kashalls/external-dns-unifi-webhook:main
          resources: {}
          imagePullPolicy: IfNotPresent
          env:
            - name: UNIFI_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: external-dns-unifi-secret
            - name: UNIFI_EXTERNAL_CONTROLLER
              value: "false"
            - name: UNIFI_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: external-dns-unifi-secret
            - name: UNIFI_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: external-dns-unifi-secret
            - name: LOG_LEVEL
              value: debug
          ports:
            - name: http-webhook
              protocol: TCP
              containerPort: 8080
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http-webhook
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /readyz
              port: http-webhook
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
