---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi-secret
  labels:
    app: external-dns
    instance: unifi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: external-dns-unifi-secret
        property: host
    - secretKey: username
      remoteRef:
        key: external-dns-unifi-secret
        property: username
    - secretKey: password
      remoteRef:
        key: external-dns-unifi-secret
        property: password
