---
# Source: external-dns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: external-dns-unifi
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: unifi
  ports:
    - name: http
      port: 7979
      targetPort: http
      protocol: TCP
    - name: http-webhook
      port: 8080
      targetPort: http-webhook
      protocol: TCP
