---
# Source: nginx-ingress/templates/admission-webhooks/cert-manager.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-ingress-root-cert
  namespace: nginx-ingress
spec:
  secretName: nginx-ingress-root-cert
  duration: "43800h0m0s"
  issuerRef:
    name: nginx-ingress-self-signed-issuer
  commonName: "ca.webhook.nginx-ingress"
  isCA: true
  subject:
    organizations:
      - nginx-ingress
---
# Source: nginx-ingress/templates/admission-webhooks/cert-manager.yaml
# generate a server certificate for the apiservices to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-ingress-admission
  namespace: nginx-ingress
spec:
  secretName: nginx-ingress-admission
  duration: "8760h0m0s"
  issuerRef:
    name: nginx-ingress-root-issuer
  dnsNames:
    - nginx-ingress-controller-admission
    - nginx-ingress-controller-admission.nginx-ingress
    - nginx-ingress-controller-admission.nginx-ingress.svc
  subject:
    organizations:
      - nginx-ingress-admission
---
# Source: nginx-ingress/templates/admission-webhooks/cert-manager.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nginx-ingress-self-signed-issuer
  namespace: nginx-ingress
spec:
  selfSigned: {}
---
# Source: nginx-ingress/templates/admission-webhooks/cert-manager.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nginx-ingress-root-issuer
  namespace: nginx-ingress
spec:
  ca:
    secretName: nginx-ingress-root-cert
