---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  annotations:
    cert-manager.io/cluster-issuer: internal
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Sonarr
    gethomepage.dev/group: Media
    gethomepage.dev/icon: sonarr.png
    gethomepage.dev/name: Sonarr
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
    gethomepage.dev/widget.type: "sonarr"
    gethomepage.dev/widget.url: "https://sonarr.lab.8none1.com"
    gethomepage.dev/pod-selector: ""
spec:
  rules:
    - host: sonarr.lab.8none1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  name: sonarr
  tls:
    - hosts:
        - sonarr.lab.8none1.com
      secretName: sonarr-ingress-tls
