---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.san.synology.com
  name: sonarr-config
  labels:
    app: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: csi.san.synology.com
    volumeHandle: f26b6e37-fd8d-44b0-8843-af232cfa0a04
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: synology-iscsi-storage
---
# Source: phpipam/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  labels:
    app: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: synology-iscsi-storage
  volumeName: sonarr-config
