apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sonarr
  name: sonarr
spec:
  serviceName: sonarr
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      initContainers:
        - name: init-config
          image: busybox:latest
          env:
            - name: URL_BASE
              value: "/sonarr"
          command:
            - sh
            - /scripts/arr-init-config.sh
          volumeMounts:
            - name: arr-init-config
              mountPath: /scripts
            - name: sonarr-config
              mountPath: /config
      containers:
        - image: linuxserver/sonarr:4.0.14
          name: sonarr
          envFrom:
            - configMapRef:
                name: arr-env
          volumeMounts:
            - mountPath: /config
              name: sonarr-config
            - mountPath: /tv
              name: tv
            - mountPath: /downloads
              name: downloads
          ports:
            - name: sonarr
              containerPort: 7878
              protocol: TCP
      volumes:
        - name: tv
          persistentVolumeClaim:
            claimName: tv
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
        - name: arr-init-config
          configMap:
            name: arr-init-config
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: media-sonarr-config
      restartPolicy: Always
