---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: default
spec:
  rules:
    - host: traefik-dashboard.lab.8none1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik
                port:
                  number: 8080
  tls:
    - hosts:
        - traefik-dashboard.lab.8none1.com
      secretName: traefik-dashboard-ingress-tls
