apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  [] # This deployment is disabled
  # - namespace.yaml
  # - crds
  # - rbac.yaml
  # - deployment.yaml
  # - service.yaml
  # - ingressclass.yaml
  # - modsecurity-deployment.yaml
  # - modsecurity-service.yaml
  # - modsecurity-middleware.yaml
