apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 36.3.0
    releaseName: traefik
    valuesFile: values.yaml
    includeCRDs: true
    namespace: traefik

resources:
  - namespace.yaml