---
apiVersion: v1
kind: Service
metadata:
  name: modsecurity
  labels:
    app.kubernetes.io/name: traefik
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: traefik
  type: ClusterIP
