# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: traefik-modsecurity
# spec:
#   plugin:
#     modsecurity:
#       MaxBodySize: "10485760"
#       ModsecurityUrl: http://modsecurity.traefik.svc.cluster.local:8080
#       TimeoutMillis: "2000"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: modsecurity-plugin
spec:
  forwardAuth:
    address: http://localhost:9090
    trustForwardHeader: true
