apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: modsecurity-plugin
spec:
  plugin:
    traefik-modsecurity-plugin:
      MaxBodySize: "10485760"
      ModsecurityUrl: http://modsecurity.traefik.svc.cluster.local:8090
      TimeoutMillis: "2000"
