apiVersion: apps/v1
kind: Deployment
metadata:
  name: modsecurity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modsecurity
  template:
    metadata:
      labels:
        app: modsecurity
    spec:
      containers:
        - name: modsecurity
          image: owasp/modsecurity-crs:4.8.0-nginx-202411071011
          ports:
            - containerPort: 8080
          env:
            - name: PARANOIA
              value: "1" # Adjust as needed
            - name: ANOMALYIN
              value: "5" # Adjust as needed
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 1000m
