---
apiVersion: v1
kind: Service
metadata:
  name: modsecurity
  labels:
    app: modsecurity
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: modsecurity
  type: ClusterIP
