apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: my-traefik-modsecurity-plugin
spec:
  plugin:
    traefik-modsecurity-plugin:
      MaxBodySize: "10485760"
      ModsecurityUrl: http://waf:80
      TimeoutMillis: "2000"
