---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
  annotations: {}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - port: 80
      name: "web"
      targetPort: web
      protocol: TCP
    - port: 443
      name: "websecure"
      targetPort: websecure
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  labels:
    app.kubernetes.io/name: traefik
  annotations: {}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - port: 8080
      name: "dashboard"
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: modsecurity
  labels:
    app.kubernetes.io/name: traefik
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app.kubernetes.io/name: traefik
  type: ClusterIP
