---
# Source: paperless-ngx/charts/gotenberg/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gotenberg
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: gotenberg
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
