---
# Source: paperless-ngx/charts/gotenberg/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: gotenberg
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: gotenberg
    app.kubernetes.io/part-of: paperless-ngx
