---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: onepassword-connect
  namespace: argocd
spec:
  project:
  source:
    repoURL: https://1password.github.io/connect-helm-charts/
    targetRevision: v1.16.0
    chart: connect
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServersideApply=true
