---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  labels:
    app: radarr
    part-of: media
  annotations:
    cert-manager.io/cluster-issuer: internal
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Radarr
    gethomepage.dev/group: Media
    gethomepage.dev/icon: radarr.png
    gethomepage.dev/name: Radarr
    gethomepage.dev/key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
    gethomepage.dev/widget.type: "radarr"
    gethomepage.dev/widget.url: "https://radarr.lab.8none1.com"
    gethomepage.dev/pod-selector: ""
spec:
  rules:
    - host: radarr.lab.8none1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  name: radarr
  tls:
    - hosts:
        - radarr.lab.8none1.com
      secretName: radarr-ingress-tls
