apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
  annotations:
    external-dns.alpha.kubernetes.io/hostname: radarr.home.8none1.com
    external-dns.alpha.kubernetes.io/target: traefik.srv.8none1.com
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.home.8none1.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: radarr
          port: http
      middlewares:
        - name: authentik-forward-auth
  tls:
    secretName: radarr-ingress-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-ingress-tls
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
spec:
  secretName: radarr-ingress-tls
  issuerRef:
    name: external
    kind: ClusterIssuer
  commonName: radarr.home.8none1.com
  dnsNames:
    - radarr.home.8none1.com
