---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-ingress-tls
  namespace: media
spec:
  secretName: radarr-ingress-tls
  issuerRef:
    name: internal
    kind: ClusterIssuer
  dnsNames:
    - radarr.lab.8none1.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-ingressroute
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.lab.8none1.com`)
      kind: Rule
      services:
        - name: authentik-outpost
          namespace: media # Specify the namespace of the service
          port: 9000 # Specify the target port
  tls:
    secretName: radarr-ingress-tls
