---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.san.synology.com
  name: radarr-config
  labels:
    app: radarr
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: csi.san.synology.com
    volumeHandle: 4aabeb35-ddf1-4e6a-9cf1-ece1e4188b5c
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: synology-iscsi-storage
---
# Source: phpipam/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  labels:
    app: radarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: synology-iscsi-storage
  volumeName: radarr-config
