apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: radarr
    app.kubernetes.io/name: radarr
    app.kubernetes.io/part-of: arrs
  name: radarr
spec:
  serviceName: radarr
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
      app.kubernetes.io/part-of: arrs
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
        app.kubernetes.io/name: radarr
        app.kubernetes.io/part-of: arrs
    spec:
      initContainers:
        - name: init-config
          image: busybox:latest
          command:
            - sh
            - /scripts/arr-init-config.sh
          volumeMounts:
            - name: arr-init-config
              mountPath: /scripts
            - name: config
              mountPath: /config
      containers:
        - image: linuxserver/radarr:5.15.1
          name: radarr
          envFrom:
            - configMapRef:
                name: arr-env
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /movies
              name: movies
            - mountPath: /downloads
              name: downloads
          ports:
            - name: radarr
              containerPort: 7878
              protocol: TCP
      volumes:
        - name: movies
          persistentVolumeClaim:
            claimName: movies
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
        - name: arr-init-config
          configMap:
            name: arr-init-config
      restartPolicy: Always
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: synology-iscsi-storage
        resources:
          requests:
            storage: 20Gi
