---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-overseerr-config-longhorn
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: media-overseerr-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-overseerr-config
  namespace: media
spec:
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  volumeName: media-overseerr-config-longhorn
  accessModes:
    - ReadWriteOnce
