apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/instance: prowlarr
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: kustomize
  name: prowlarr
spec:
  serviceName: prowlarr
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
      app.kubernetes.io/instance: prowlarr
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: media
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
        app.kubernetes.io/instance: prowlarr
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: media
    spec:
      initContainers:
        - name: init-config
          image: busybox:latest
          command:
            - sh
            - /scripts/arr-init-config.sh
          volumeMounts:
            - name: arr-init-config
              mountPath: /scripts
            - name: prowlarr-config
              mountPath: /config
      containers:
        - image: linuxserver/prowlarr:1.37.0
          name: prowlarr
          envFrom:
            - configMapRef:
                name: arr-env
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
          ports:
            - name: prowlarr
              containerPort: 9696
              protocol: TCP
      volumes:
        - name: arr-init-config
          configMap:
            name: arr-init-config
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: media-prowlarr-config
      restartPolicy: Always
