---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-data
  labels:
    app: paperless-ngx
    part-of: paperless-ngx
    volume: paperless-ngx-data
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - sync
  nfs:
    path: /volume1/Filing
    server: 172.16.0.5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
  labels:
    app: paperless-ngx
    part-of: paperless-ngx
    volume: paperless-ngx-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: paperless-ngx
      volume: paperless-ngx-data
  resources:
    requests:
      storage: "10Gi"
