---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paperless-ngx
  labels:
    app: paperless-ngx
    part-of: paperless-ngx
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paperless-ngx
  labels:
    app: paperless-ngx
    part-of: paperless-ngx
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paperless-ngx
  labels:
    app: paperless-ngx
    part-of: paperless-ngx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paperless-ngx
subjects:
  - kind: ServiceAccount
    name: paperless-ngx
