---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-general
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: secretKey
      remoteRef:
        key: paperless-ngx-config
        property: secretKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-admin
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
    template:
      type: "kubernetes.io/basic-auth"
  data:
    - secretKey: username
      remoteRef:
        key: paperless-ngx-config
        property: admin-username
    - secretKey: password
      remoteRef:
        key: paperless-ngx-config
        property: admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-redis-auth
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: paperless-ngx-config
        property: redis-auth-uri
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-postgresql-auth
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: postgres-user
      remoteRef:
        key: paperless-ngx-config
        property: postgres-user
    - secretKey: postgres-user-password
      remoteRef:
        key: paperless-ngx-config
        property: postgres-user-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-smtp-auth
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
    template:
      type: "kubernetes.io/basic-auth"
  data:
    - secretKey: username
      remoteRef:
        key: paperless-ngx-config
        property: email-username
    - secretKey: password
      remoteRef:
        key: paperless-ngx-config
        property: email-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-oauth
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/managed-by: kustomize
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_APPS
      remoteRef:
        key: paperless-ngx-config
        property: PAPERLESS_APPS
    - secretKey: PAPERLESS_SOCIALACCOUNT_PROVIDERS
      remoteRef:
        key: paperless-ngx-config
        property: PAPERLESS_SOCIALACCOUNT_PROVIDERS
