---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptimekuma-config-longhorn
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: uptime-kuma
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: uptime-kuma
    app.kubernetes.io/managed-by: kustomize
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: uptimekuma-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-config
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: uptime-kuma
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: uptime-kuma
    app.kubernetes.io/managed-by: kustomize
spec:
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  volumeName: uptimekuma-config-longhorn
  accessModes:
    - ReadWriteOnce
