---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-info
  namespace: "synology-csi"
  labels:
    app.kubernetes.io/name: synology-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-clustersecretstore
  target:
    creationPolicy: Owner
  data:
    - secretKey: client-info.yml
      remoteRef:
        key: synology-csi-clientinfo.yaml
        property: client-info.yml
