---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synology-csi

resources:
  - namespace.yaml
  # RBAC
  - node-rbac.yaml
  - controller-rbac.yaml
  # ExternalSecret
  - externalsecret.yaml
  # Controller STS and Node DaemonSet
  - controller-sts.yaml
  - node-daemonset.yaml
  # CSI Driverk
  - csi-driver.yaml
  # StorageClass
  - storageclass.yaml
  # Snapshotter
  - snapshotter
