apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  labels:
    app: synology-csi
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
# if all params are empty, synology CSI will choose an available location to create volume
parameters:
  dsm: "172.16.2.5"
  location: "/volume1"
  fsType: "ext4"
reclaimPolicy: Retain
allowVolumeExpansion: true
